app = "cicero"
primary_region = "iad"

kill_timeout = "300s"

[build]
  dockerfile = "Dockerfile"
  ignorefile = ".dockerignore"

[env]
  PYTHONUNBUFFERED = "1"

[[vm]]
  memory = "4gb"
  cpu_kind = "shared"
  cpus = 2

[deploy]
  strategy = "bluegreen"

[[checks]]
name = "healthcheck"
type = "tcp"
interval = "10s"
timeout = "2s"
grace_period = "5s"
port = 8081